name: BETA Build and Deploy

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Get licenses
        run: |
          curl "https://firebasestorage.googleapis.com/v0/b/quantified-self-io.appspot.com/o/assets%2Flicenses.json?alt=media&token=470a21d4-571d-432d-a6f6-95df7a24de33" --create-dirs -o licenses.json

      - name: Install and test functions
        run: |
          cd functions
          npm ci
          npm run test
          npm run build
          cd ..

      - name: Install, test and build
        run: |
          npm ci
          npm run test
          npm run build-beta

      - name: Get fonts
        run: |
          curl "https://firebasestorage.googleapis.com/v0/b/quantified-self-io.appspot.com/o/assets%2Ffonts%2Fproxima-nova-regular.woff?alt=media&token=17c6e5ba-1a2f-4bdd-af56-b467b754f0be" --create-dirs -o dist/assets/fonts/proxima-nova-regular.woff
          curl "https://firebasestorage.googleapis.com/v0/b/quantified-self-io.appspot.com/o/assets%2Ffonts%2Fproxima-nova-regular.woff2?alt=media&token=8caf4bf3-4d07-4240-bfe7-5234f3f65408" --create-dirs -o dist/assets/fonts/proxima-nova-regular.woff2

      - name: Create SA key
        run: echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > "${{ runner.temp }}/firebase_service_account.json"

      - name: Deploy to Firebase
        run: |
          npm install -g firebase-tools
          export GOOGLE_APPLICATION_CREDENTIALS="${{ runner.temp }}/firebase_service_account.json"
          firebase deploy --only hosting:beta
